### ISSUE TITLE
Install new version of RT and migrate existing RT content to the new server

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork.maa.org#1]
Transferring RT might be straightforward because as Tani says it is still actively maintained.  I found pretty
good instructions here:  

 https://rt-wiki.bestpractical.com/wiki/MigrateToNewServer
https://forum.bestpractical.com/t/rt-3-x-migration-to-new-server/13747

also here:  https://docs.bestpractical.com/rt/4.4.4/backups.html#Restoring-from-backups
https://bestpractical.com/download-page 

The new server is running Ubuntu 18.04. 

The version of RequestTracker (RT) is 3.8 and the current version is 4.4  stable

**Comment by mgage** [comment]
This has been done -- there is still some need to tweak the configuration.
