### ISSUE TITLE
email not being accepted -- fix bounced email from test1.webwork.maa.org

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork.maa.org#13]
Looking at the logs for this I get:

Looking at the logs for this I get:

Feb 12 16:55:12 test1 postfix/smtp[2994]: DF2EF7E73E: to=<pstaab@fitchburgstate.edu>, 

relay=aspmx.l.google.com
[172.217.197.27]:25, delay=0.64, delays=0.01/0/0.13/0.5, dsn=5.7.1, status=bounced (host aspmx.l.google.com
[172.217.197.27] said: 550-5.7.1 [34.204.106.157      
- 12] Our system has detected that this message is 550-5.7.1 likely unsolicited mail. To reduce the amount of spam sent to Gmail, 550-5.7.1 this message has been blocked. 
- Please visit 550-5.7.1  https://support.google.com/mail/?p=UnsolicitedMessageError 550 5.7.1  for more information. h8si472144qvb.117 - gsmtp (in reply to end of DATA command))

Note: Fitchburg State recently moved to gmail for mail, so that's why I'm guessing this message popped up.  I was trying to determine how to stop this from happening.  Looks like there is a site: postmaster.google.com that handles some of this.  Have you done this Mike, if not, I can try to figure this out.

**Comment by taniwallach** [comment]
See https://github.com/openwebwork/webwork.maa.org/issues/10 - I suspect that proper SPF and reverse DNS records will help, at least to some extent.

**Comment by mgage** [comment]
This works minimally for now.   I'll set up the SPF and DNS recommendations as a separate issue.
