### ISSUE TITLE
request tracker (rt) is partially installed but needs web interface set up

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork.maa.org#16]
I have the basic software and the cpan modules installed.

There is one glitch with gpg module (security) that needs further work.

The connection with the web (configuring apache) is not yet in place.

It's possible that the database is not perfectly set up -- the upgrade process was a little rough.

It's sure that it is missing data since January 20 about

**Comment by taniwallach** [comment]
I got the web server available at https://test1.webwork.maa.org/rt/  and was able to log in.

I was able to install `GnuPG::Interface` using the Ubuntu package, but additional configuration is needed to get GPG working so I left it disabled for now.

**Comment by mgage** [comment]
now to configure the users, queues, mail lists and so forth.

**Comment by mgage** [comment]
Thanks to Tani and Glenn to helping with this.
