### ISSUE TITLE
Transfer front landing site from webwork.maa.org to test1.webwork.maa.org

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork.maa.org#17]
Danny is going to do this.

**Comment by dlglin** [comment]
Front page and related content have been migrated.
Standardized permissions (all files owned by www-data:www-data with permission 664).
Deleted orphaned, backup and test files.
Check that all content at test1.webwork.maa.org appears properly.

Will open separate issues for things that still need to be addressed.
