### ISSUE TITLE
summary of progress made on transferring from webwork.maa.org to new server (currently test1.webwork.maa.org)

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork.maa.org#26]
Progress has been made particularly in transferring all or most of the basic data but there is still a lot of work to be done  in configuring the new site — in particular in getting the email reporting working properly.

### bugzilla
* bugzilla is at  https://test1.webwork.maa.org/bugzilla
	* login and test it
	* posts to bugs.webwork.maa.org are  currently directed to https://test1.webwork.maa.org/bugzilla
        * bugzilla mostly seems to be working (see comments from George Jennings)
        * There are posts missing between December 5 and February 23.  
		* Rather than try to retransfer and rebuild the entire database from webwork.maa.org I was thinking of resubmitting the posts between December 5, 2019 and February 23, 2020 from the emails that have piled up in my inbox.  
		* Transferring and rebuilding the database seemed to be easier for bugzilla than for the moodle forums, but it still might be time consuming.  I don’t know if just adding the missing records to the appropriate table in the bugzilla database would work — it failed with the moodle forums — there were too many cross references.
	* email reporting seems to work.

### rt
* rt  is at https://test1.webwork.maa.org/rt
	* rt seems to work also — login and test it — I can provide passwords and accounts for testers if you don’t have them
        * rt is currently accepting messages sent to webwork.maa.org
	* !!!    I have not yet figured out how to have messages received into the webwork.maa.org “general” queue 

broadcast to the webwork development list e.g. [rt.webwork.maa.org……..]  for example:
	![PastedGraphic-1](https://user-images.githubusercontent.com/1203580/75126196-d2c5b480-5686-11ea-8df7-92ee9d0e0b17.png)

this is what the previous emails looked like, coming in to my mail box.  Now none are delivered although posts appear in the rt queues

### wiki 
* wiki:  is at https://test1.webwork.maa.org/wiki  also at https://test1.webwork.maa.org/new_mediawiki (the first address is aliased to the second)
      *  This is set up with most if not all of the content of the original wiki
       * The authentication system seems to be set up properly.  It’s possible that you may have to request to reset your password
           *  (I think you can reset it to the original if you want) but it should work properly after that.  The method of encrypting passwords has changed several times over the last 8 years so I consider it fortunate that it works this well.
* The wiki needs a lot of long term maintenance.  In particular many of the extensions have not been upgraded and installed.  There are many broken links and in general there is a lot of technical debt on that site.  The content is badly in need of curation as well.

*  First project is to update the extensions I think.

### moodle
* moodle: is at https://test1.webwork.maa.org/moodle and at https://test1.webwork.maa.org/moodle38  
       *  (this link needs to be removed and the directory moodle38 renamed to moodle if we want RESTFUL access to pages in moodle.

      * This was the most difficult transfer.  I have rebuilt the database twice upgrading from moodle 1.9 through moodle 2.2 then 2.5 then 2.8 then 3.1 then 3.5 then 3.5.10 then 3.8.  Moodle 1.9 through 3.1 requires php5.  moodle 3.5.10 requires php 7.0 and php 3.8 requires php 7.1 or higher.
      * Thanks to all who provided help and suggestions with this.
       * Glenn Rice figured out how to up-date the single sign on in Moodle so that it could handle the new encryption in the wiki
      * The single sign on from the wiki should work.  
       *  There are a lot of new configuration choices that need to be made. I’ve temporarily accepted defaults.  It looks like you can now change your login (recorded in the wiki database) from Moodle. Maybe you can even register from there. The message allowing you reset you password gets sent from moodle to the wiki but it is a bit confusing as to what happens then.
        * I have added an email sign up to the wiki for the interim in case the single sign on configuration fails.

        * This is a good project for someone to test all of the paths they can think of for signing on to the wiki and to moodle (which houses the forums) and making a record of what works and what doesn’t so that programmers can set configurations so that the sign-on to the two apps appears simple (even though it’s not!).

* I’ve redirected wiki, moodle and rt from webwork.maa.org to https://test1.webwork.maa.org.  I’m not sure I have done it completely correctly.

### drupal
* The drupal site at http://openwebwork.org is likely to disappear.  I’ve rescued the bibliography list, but not much else.  If any one
wants to revive the drupal site (it was intended to be the front end for webwork.maa.org but we didn’t find a maintainer to keep it up) should
 let me know soon.  Anyone interested?

### planet   
	* the list of blogs is saved.
       *  Tani is going to put up the latest version of this — it’s probably not so urgent since there is little data saved on webwork.maa.org but having all of those blog posts available in one spot is valuable — although most of them can be found by google search.
        * planet was originally installed  at /var/www/planet on webwork.maa.org
        * I think a good place for the new planet would be /var/www/html/planet    on test1.webwork.maa.org

### postfix
* postfix (sendmail), ssl certificates, getting our spam rating lowered!!
	* I have it minimally working, but I suspect that some of the problems with rt and email are due to inadequate configuration of postfix.
        * Glenn Rice has installed temporary certificates but once reset the DNS pointers we’ll want to get new ones.
        * A remaining project is to redirect the DNS  “webwork.maa.org” to the box currently named “test1.webwork.maa.org” and point “old.webwork.maa.org” to the  old “webwork.maa.org”  .  Then we will have to reconfigure a lot of site names in the configuration files in the  folders /var/www/html and /opt/rt   to match the changes in the address.

**Comment by dlglin** [comment]
Since we are now live with the new site and accounts are not working consistently I'd like to put up a message on the various landing pages letting people know that we are still working on things.

What sort of instructions make sense to post for people who are having trouble? Submit a GitHub issue?  Do we want to put an email address?

**Comment by mgage** [comment]
_What sort of instructions make sense to post for people who are having trouble? Submit a GitHub issue? Do we want to put an email address?_

Hi Danny,
I suggest posting a message indicating that they can submit a github message (the downside is that they probably have to sign up for github) and as an alternative sending an email message to the "technical manager" -- namely you.  :-)

**Comment by mgage** [comment]
Update:
The new server is at the address   webwork.maa.org   (test1.webwork.maa.org will also work for a little while longer but will disappear eventually).  The old webwork.maa.org server is no longer available.

The addressing issues on this page are resolved except for planet which has not yet been set up.
See README at https://github.com/openwebwork/webwork.maa.org
