### ISSUE TITLE
Emails from wiki have a from address of "apache@🌻.invalid"

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork.maa.org#29]
When I sign up for a new wiki account, I get an email confirmation from "apache@🌻.invalid".  It looks like this is set in /var/www/html/new_mediawiki/LocalSettings.php.

The variables $wgEmergencyContact and $wgPasswordSender should be set to a more meaningful email address, preferably one that is tracked by rt.

**Comment by drgrice1** [comment]
Now these emails will come from apache@webwork.maa.org.  I am not sure what these addresses should be set to, but emails from this address at least go through.  gmail was completely blocking the old address.

**Comment by mgage** [comment]
Fixed by @drgrice1
