### ISSUE TITLE
The new wiki refers to itself as "new_mediawiki"

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork.maa.org#30]
When emails are sent from the wiki the subject says something like "new_mediawiki email address confirmation", which isn't very descriptive of which wiki they are from.

I believe that this is based on the variable $wgSitename in /var/www/html/new_mediawiki/LocalSettings.php.  I suggest changing this to something like "WeBWorK Wiki".  Does anyone know if this will have other consequences for the wiki config?

**Comment by mgage** [comment]
I have set this to:
$wgSitename = "WeBWorK_wiki";
$wgMetaNamespace = "The WeBWorK Project wiki";


You can check this at: https://webwork.maa.org/wiki/MediaWiki:Aboutsite

So far it doesn't seem to cause trouble.
