### ISSUE TITLE
RSS feed address needs to be fixed 

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork.maa.org#32]
Upper right corner of main page of wiki

Failed to load RSS feed from http://webwork.maa.org/moodle/rss/file.php/3/5/forum/31/rss.xml: Error parsing XML for RSS

**Comment by drgrice1** [comment]
I have fixed the feed on the wiki page, but for some reason the links in the feed itself are still pointing to test1.webwork.maa.org.  I think this is a Moodle issue.

**Comment by drgrice1** [comment]
The links in the feed are working now.  Did someone fix that, or did it fix itself when another post was made?

**Comment by mgage** [comment]
I poked around on the forums to see if there was some kind of cache or permalink but I couldn't find anything.  I made the new post to bring things slightly more up to date.
That probably fixed things but I'm not sure why.

**Comment by drgrice1** [comment]
I guess that Moodle regenerated the rss feed when the post was made.  I should note that I also changed the hostname of the server from test1.webwork.maa.org to webwork.maa.org using hostnamectl and by editing the /etc/hosts file.  The Moodle scripts may use that hostname for its links in the feed.

**Comment by mgage** [comment]
Thanks Glenn.
