### ISSUE TITLE
bugzilla configuration

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork.maa.org#36]
Bugzilla doesn't seem to be working with cookies. (I've tried with two browsers and done various combinations of emptying cache.

1. login at https://bugs.webwork.maa.org/ . (the upper bar will register your email address and "logout"
2. click home -- all data will have been forgotten.
3. OR . click "all bugs" and you will be asked to login again. "bugzilla needs a legitimate login..."
is anyone else experiencing this phenomenon?

**Comment by drgrice1** [comment]
I see this too.  I probably didn't reconfigure everything correctly when I changed from webwork.maa.org/bugs to bugs.webwork.maa.org.

**Comment by drgrice1** [comment]
I believe this is fixed now.  The file buzilla/data/params.json had the cookiepath set to "/bugzilla", but now the site is at the root of the domain.  So it needed to be changed to "/".

**Comment by mgage** [comment]
This fixed it for my chrome browser but not for firefox — even after I shut down firefox and restarted it.  (And also erased all cookies for bugs.webwork.maa.org <http://bugs.webwork.maa.org/>)

— Mike

**Comment by drgrice1** [comment]
That is odd.  Firefox is the browser I tested this on.

**Comment by mgage** [comment]
the firefox browser on my home computer does fine so it must be some kind of cache on my work machine.
