### ISSUE TITLE
Investigate shared sign-on between Moodle and Mediawiki

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork.maa.org#4]
This needs more research and some advice from Jason Aubrey who set up the original SSO between the two.  

At the time Moodle could simply read the encryption (MD5) in the password field in the mediawiki database. 

Now apparently it can’t, at least automatically.   mediawiki has switched switched to something called bcrypt.

1. Both moodle and mediawiki have many extensions implementing SSO on different platforms but I haven’t yet found
one that connects moodle and mediawiki.  I haven’t completed an exhaustive search. One solution is to find or tweak one of these
so that moodle can again look up the username and password in the wiki database. 

2. We could do the opposite — have people sign on to Moodle and have the wiki look up user names and passwords in the moodle database.
	a. This is probably closer to what people expect — they are usually surprised to find that they have to sign up on the wiki first.

3. We can enable email sign on in Moodle (not available in mediawiki AFAIK). I _think_ we can preserve user names, important to keep these
connected to forum posts, and just have people request a new password with “forgot password”.  But this is not well tested yet.

4. We can abandon single sign on between the two, at least for now?

5. Other ideas?  LDAP is a possibility but it’s one more application, and I’m not sure how easy it would be to preserve current user names and their link to forum posts.

**Comment by dlglin** [comment]
Mike,

I managed to get moodle working with the passwords from the mediawiki database.  I added lines 141-145 of auth.php and line 98 of settings.php in /var/www/html/moodle/auth/db.  I created a user on the new_mediawiki site, and then was able to sign in with that user in moodle.

Glenn

**Comment by mgage** [comment]
This still needs more testing but it seems likely that this password setup will work -- the worst case is that a user has to request a reset of their password with "forgot password".

**Comment by mgage** [comment]
We seem to have single sign on working between forum and wiki
