### ISSUE TITLE
get thumbnails working on mediawiki_new

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork.maa.org#46]
We currently have two mediawiki's set up.

https://webwork.maa.org/wiki   links to /var/www/html/mediawiki
https://webwork.maa.org/mediawiki_new   links to /var/www/html/mediawiki_new

For the latter the thumbnails are not showing up?  This might be because we only have redirect from wiki to mediawiki  and no redirect from wiki to mediawiki_new.

**Comment by drdrew42** [comment]
Mischief managed.

**Comment by drgrice1** [comment]
Thanks for taking care of this Drew.  I was going to get to it, but have been busy figuring out the rest of the semester here.

**Comment by drdrew42** [comment]
Happy to pitch in - it's been rough for everyone, and you've already handled a bunch of this work... so right back at'cha!
