### ISSUE TITLE
Testing MediaWiki Passwords

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork.maa.org#5]
sorry — I mistyped   -it’s the extension connecting to bugzilla reports that is missing.

The new wiki is at 

https://test1.webwork.maa.org/new_mediawiki

First of all test login methods
	Can you login with your old password?
        Can you create a new account (alert me so that I can ok your application)
        Do you get email notification?
        Can you do a “forgot password” and does that notify you and allow you to reset your password? 
               (this doesn’t work for me.  It’s hard to test because you can only submit one request every 24 hours. 
        

You can also look around the wiki and see what is missing.  I know for sure that some of the extensions — such as connection to the login
page are missing.

Take care,

Mike

**Comment by dlglin** [comment]
Thanks for checking on the media wiki passwords.  They seem to be working acceptably except for the occasional bounced emails.

I’ve seen posts similar to this before but haven’t resolved them.  I think webwork.maa.org site has a bad reputation for spam (this dates back at least 
a year) so this might be causing it.  It’s something we’ll have to resolve once we have everything switched over.

Take care,

Mike

On Feb 12, 2020, at 12:18 PM, Peter Staab <peter.staab@gmail.com> wrote:

Looking at the logs for this I get:

Feb 12 16:55:12 test1 postfix/smtp[2994]: DF2EF7E73E: to=<pstaab@fitchburgstate.edu>, relay=aspmx.l.google.com[172.217.197.27]:25, delay=0.64, delays=0.01/0/0.13/0.5, dsn=5.7.1, status=bounced (host aspmx.l.google.com[172.217.197.27] said: 550-5.7.1 [34.204.106.157      12] Our system has detected that this message is 550-5.7.1 likely unsolicited mail. To reduce the amount of spam sent to Gmail, 550-5.7.1 this message has been blocked. Please visit 550-5.7.1  https://support.google.com/mail/?p=UnsolicitedMessageError 550 5.7.1  for more information. h8si472144qvb.117 - gsmtp (in reply to end of DATA command))

Note: Fitchburg State recently moved to gmail for mail, so that's why I'm guessing this message popped up.  I was trying to determine how to stop this from happening.  Looks like there is a site: postmaster.google.com that handles some of this.  Have you done this Mike, if not, I can try to figure this out. 

I'll keep poking around...

**Comment by taniwallach** [comment]
Old Wiki password allowed me in, and needed to be changed (to short) but neither allowed me into the new Moodle. A Wiki page was edited successfully.

Account creation worked, and the new account could also access the new Moodle. The email confirmation letter from Moodle arrived in Span to the Gmail accounts used - but the link worked.

Password reset email requested form the Wiki did not arrive.

**Comment by dlglin** [comment]
Was able to log in to the wiki with my old password.  Can't log in to Moodle.

Created a new account in the wiki.  New account also can't log into Moodle.

@mgage Have you re-enabled the shared passwords since you rebuilt Moodle?

**Comment by mgage** [comment]
The single sign on seems to work pretty well for the moment.  The initial sign on for those who have not used the wiki/forum in months might not work, but if they request a password change and fill that in (even with the old password) then things should be ok after that.
