### ISSUE TITLE
Some Moodle forum posts do not load - Exporter class is missing required related data:

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork.maa.org#6]
Several posts I looked at hit the same error:
  - https://test1.webwork.maa.org/moodle/mod/forum/discuss.php?d=4694
  - https://test1.webwork.maa.org/moodle/mod/forum/discuss.php?d=4707
  - https://test1.webwork.maa.org/moodle/mod/forum/discuss.php?d=4698

```
Coding error detected, it must be fixed by a programmer: Exporter class is missing required related data: (mod_forum\local\exporters\post) author =&gt; mod_forum\local\entities\author

More information about this error
Debug info:
Error code: codingerror
￼×Stack trace:
line 106 of /lib/classes/external/exporter.php: coding_exception thrown
line 59 of /mod/forum/classes/local/exporters/post.php: call to core\external\exporter->__construct()
line 144 of /mod/forum/classes/local/exporters/posts.php: call to mod_forum\local\exporters\post->__construct()
line ? of unknownfile: call to mod_forum\local\exporters\posts->mod_forum\local\exporters\{closure}()
line 148 of /mod/forum/classes/local/exporters/posts.php: call to array_map()
line 125 of /lib/classes/external/exporter.php: call to mod_forum\local\exporters\posts->get_other_values()
line 173 of /mod/forum/classes/local/builders/exported_posts.php: call to core\external\exporter->export()
line 98 of /mod/forum/classes/local/renderers/posts.php: call to mod_forum\local\builders\exported_posts->build()
line 210 of /mod/forum/classes/local/renderers/discussion.php: call to mod_forum\local\renderers\posts->render()
line 340 of /mod/forum/discuss.php: call to mod_forum\local\renderers\discussion->render()
```

**Comment by mgage** [comment]
This is a recognized bug in Moodle 3.8. -- you can reach these posts by searching for the title. 
 https://tracker.moodle.org/browse/MDL-66292

**Comment by taniwallach** [comment]
> This is a recognized bug in Moodle 3.8. -- you can reach these posts by searching for the title.
> https://tracker.moodle.org/browse/MDL-66292

If so, we apparently need to live with this issue for now - but as it makes forum use quite inconvenient - maybe some obvious warning should be added somewhere above the list of forum posts in the more active forums. Ex. below the line
```
Questions and comments regarding day-to-day use of WeBWorK.
```
at https://test1.webwork.maa.org/moodle/mod/forum/view.php?id=3

Proposed text:

> Due to a Moodle bug, some forum posts do not load when you click the title of the tread, and the error  `Coding error detected, it must be fixed by a programmer: Exporter class is missing required related data: ...` is displayed. In such cases, we recommend you paste the thread title into the search box, as the search results will show the relevant messages.

---
Can someone sign up to Moodle's bug tracker to (a) report that we hit this issue as there is a comment there that 3.7.4+ does not hit the isse ("Simey Lameze added a comment - 06/Feb/20 11:40 AM"), and (b) to watch the issue so we will be aware of when a fix becomes available.

**Comment by mgage** [comment]
Fixed by reimporting the database and upgrading one step at a time from moodle 1.9 to 3.8
