### ISSUE TITLE
Moodle - (excess warning messages) SQL junk displayed after saving profile

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork.maa.org#9]
After saving the profile for a new account created via the Wiki and used to log in to Moodle:

```
mysqli): SELECT LOWER(user_name) AS F0 FROM user WHERE LOWER(user_name) = 'taniwallach'
(mysqli): SET NAMES 'utf8'
```

Show HTML source showed:
```
<hr>
(mysqli): SET NAMES 'utf8' &nbsp;
<hr>
<hr>
(mysqli): SELECT LOWER(user_name) AS F0
                     FROM user
                     WHERE LOWER(user_name) = 'taniwallach' &nbsp;
<hr>
<hr>
(mysqli): SET NAMES 'utf8' &nbsp;
<hr>
<!DOCTYPE html>

<html  dir="ltr" lang="en" xml:lang="en">
<head>
    <title>moodleMAA: Edit profile</title>
```

**Comment by mgage** [comment]
the error reporting on moodle is currently set to verbose -- this will go away when we reset that

**Comment by taniwallach** [comment]
> the error reporting on moodle is currently set to verbose -- this will go away when we reset that

Great - so we know what to turn off before the system goes into production, and can close the issue now or after that is done.

**Comment by mgage** [comment]
I believe that this problem is currently solved.  The warnings on moodle are still set pretty high while we seek to squash the last bugs.
